//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruelo.Api.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public long Id { get; set; }
        public long IdMarca { get; set; }
        public long IdTipoArticulo { get; set; }
        public long IdRubro { get; set; }
        public Nullable<long> IdSubrubro { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public string CodigoAlternativo { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Subrubro Subrubro { get; set; }
        public virtual TipoArticulo TipoArticulo { get; set; }
    }
}
